# Numpy Operations

In [19]:
import numpy as np
x = np.array([4,5,6])
x1 = np.array([7,8,9])
x - x1

array([-3, -3, -3])

In [20]:
x = [2,3,4]
x1 = [9,8,7]
x + x1

[2, 3, 4, 9, 8, 7]

In [4]:
import numpy as np
array = np.arange(11,20).reshape(3,3)
array

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [5]:
array * 2

array([[22, 24, 26],
       [28, 30, 32],
       [34, 36, 38]])

In [6]:
array + array

array([[22, 24, 26],
       [28, 30, 32],
       [34, 36, 38]])

In [7]:
array * array

array([[121, 144, 169],
       [196, 225, 256],
       [289, 324, 361]])

In [8]:
array - array

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [9]:
array ** 2

array([[121, 144, 169],
       [196, 225, 256],
       [289, 324, 361]], dtype=int32)

In [15]:
import numpy as np 
a = np.array([[4,2],[6,3]])
a

array([[4, 2],
       [6, 3]])

In [16]:
b = np.array([[7,2],[4,3]])
b

array([[7, 2],
       [4, 3]])

In [17]:
np.dot(a,b)

array([[36, 14],
       [54, 21]])

In [18]:
a * b

array([[28,  4],
       [24,  9]])